[package]
name = "Bridge"
version = "0.0.1"
edition = "2024.beta"

[dependencies]
MoveStdlib = { local = "../../../crates/sui-framework/packages/move-stdlib" }
Sui = { local = "../../../crates/sui-framework/packages/sui-framework" }

[addresses]
bridge = "0x0"
