# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/schema/pg.rs"
patch_file = "src/schema/pg.patch"

[migrations_directory]
dir = "migrations/pg"
